GET http://localhost:5000/users/

###

POST http://localhost:5000/users
Content-Type: application/json

{
    "email": "Bandi",
    "password": "Bandi",
    "subscription": false
}

###

POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "true@true.com",
    "password": "true"
}

###

PUT http://localhost:5000/users/change
Content-Type: application/json

{
    "userId" : "yaVGnVSo_sAh99TGPQ5dq",
    "subscription": false
}

###

DELETE http://localhost:5000/users
Content-Type: application/json

